project:
  type: book
  output-dir: output
book:
  title: Tesis de Maestría
  date: Abril, 2024
  lang: es
  author:
    name: CluadioSCastillo
    url: https://castillosebastian.com/
  downloads: [pdf]
  abstract: "La disponibilidad de datos muestrales afecta a los procesos de selección de características, y resulta particularmente condicionante en escenarios de alta dimensionalidad y bajo número de muestras. En el caso de selección de características mediante AGs la falta de datos muestrales impacta negativamente en la función de aptitud, y de esa forma limita la eficacia del algoritmo. Por eso, la técnica de aumentación de datos mediante AVs plantea una posible solución a este problema, ofreciendo distintas alternativas de implementación en el contexto de los AGs."
  chapters:
    - index.qmd    
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd  
  repo-url: https://github.com/castillosebastian/ealab
  repo-actions: [edit, source, issue]
  search: true
thesis:
  supervisor: 
    name: MatíasGerard/LeandroVignolo
    url: https://quarto.org/
  degree-name: Maestría en Minería de Datos
  university: Universidad Tecnológica Nacional 
  department: Seccional Paraná
  group: Posgrado
  faculty: Computación
  declaration: "Frontmatter/declaration.tex"
  quotation:
    text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
    attribution: Dave Barry
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2

