project:
  type: book
  output-dir: output
book:
  title: Generación de datos sintéticos para selección de características con algoritmos genéticos
  date: Marzo, 2025
  lang: es
  author:
    name: Claudio Sebastian Castillo
    url: https://castillosebastian.com/
  downloads: [pdf]
  abstract: "En problemas de aprendizaje automático, la disponibilidad de datos muestrales influye significativamente en los procesos de selección de características, volviéndose especialmente crítica en escenarios de alta dimensionalidad, escaso número de muestras y presencia de ruido. Cuando la selección se realiza mediante Algoritmos Genéticos (AG), la falta de datos impacta negativamente en la función de aptitud, limitando así la eficacia del algoritmo. Para abordar este problema, proponemos integrar el proceso de selección de características con un paso previo de generación sintética de datos mediante Autocodificadores Variacionales (AV). Este enfoque permite aumentar de forma artificial la información disponible. El flujo de procesamiento resultante combina AV y AG, y los aplica a procesos de selección exigentes. De esta forma, se obtienen mejores resultados en comparación con el procesamiento sin aumentación. En este estudio se detalla la integración de AV y AG, y se describen los experimentos realizados sobre cinco conjuntos de datos ampliamente utilizados en la literatura: *Leukemia*, *Gisette*, *Mandelon*, *GCM* y *All Leukemia*. Asimismo, se presentan las arquitecturas de los modelos empleados en la integración."
  chapters:
    - index.qmd    
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd  
    - Appendices/AppendixB.qmd
  repo-url: https://github.com/castillosebastian/ealab
  repo-actions: [edit, source, issue]
  search: true
thesis:
  supervisor: 
    name: Matías Gerard y Leandro Vignolo
    url: https://sinc.unl.edu.ar/
  degree-name: Maestría en Minería de Datos
  university: Universidad Tecnológica Nacional 
  department: Seccional Paraná
  group: UTN     
  quotation:
    text: A mi corazón de 4/4; Morella, Sofía, Joquín y Manuel. A mi musa Verónica.    
  acknowledgements: "Frontmatter/acknowledgements.tex"  
  logo: images/utn_logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2

