project:
  type: book
  output-dir: output
book:
  title: Generación de datos sintéticos para selección de características con algoritmos genéticos
  date: Septiembre, 2024
  lang: es
  author:
    name: Claudio Sebastian Castillo
    url: https://castillosebastian.com/
  downloads: [pdf]
  abstract: "La disponibilidad de datos muestrales afecta los procesos de selección de características, y resulta particularmente condicionante en escenarios de alta dimensionalidad y bajo número de muestras. En el caso de selección de características mediante Algoritmos Genéticos la falta de datos impacta negativamente en la función de aptitud, y de esa forma limita la eficacia del algoritmo. Por eso, la técnica de aumentación de datos mediante Autocodificadores Variacionales plantea una posible solución a este problema, ofreciendo distintas alternativas de implementación en el contexto de los Algoritmos Genéticos."
  chapters:
    - index.qmd    
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd  
    - Appendices/AppendixB.qmd
  repo-url: https://github.com/castillosebastian/ealab
  repo-actions: [edit, source, issue]
  search: true
thesis:
  supervisor: 
    name: Matías Gerard y Leandro Vignolo
    url: https://sinc.unl.edu.ar/
  degree-name: Maestría en Minería de Datos
  university: Universidad Tecnológica Nacional 
  department: Seccional Paraná
  group: UTN     
  quotation:
    text: A mi corazón de 4/4; Morella, Sofía, Joquín y Manuel. A mi musa Verónica.    
  acknowledgements: "Frontmatter/acknowledgements.tex"  
  logo: images/utn_logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2

