project:
  type: book
  output-dir: output
book:
  title: Generación de Datos Sintéticos para Selección de Características con Algoritmos Genéticos
  date: Mayo, 2025
  lang: es
  author:
    name: Claudio Sebastian Castillo
    url: https://castillosebastian.com/
  downloads: [pdf]
  abstract: |
    En problemas de aprendizaje automático, la disponibilidad de datos muestrales influye significativamente en los procesos de selección de características, volviéndose especialmente crítica en escenarios de alta dimensionalidad y presencia de ruido. En general, cualquier método de selección de características es sensible a la cantidad de datos disponibles. Cuando la selección se realiza mediante Algoritmos Genéticos (AG), la falta de datos impacta negativamente en la función de aptitud, limitando así la eficacia del algoritmo. Para abordar este problema, proponemos integrar el proceso de selección de características con un paso previo de generación sintética de datos mediante Autocodificadores Variacionales (AV). Este enfoque permite aumentar de forma artificial la información disponible. El flujo de procesamiento resultante combina AV y AG, y los aplica a procesos de selección exigentes. De esta forma, se obtienen mejores resultados en comparación con el procesamiento sin aumentación. En este estudio se detalla la integración de AV y AG, y se describen los experimentos realizados sobre cinco conjuntos de datos ampliamente utilizados en la literatura: *Leukemia*, *Gisette*, *Mandelon*, *GCM* y *ALL Leukemia*. Asimismo, se presentan las arquitecturas de los modelos empleados en la integración.

    \newpage

    \begin{center}
    {\fontsize{20}{24}\selectfont\textbf{Abstract}}
    \end{center}

    \begin{center}
    \textbf{Synthetic Data Generation for Feature Selection with Genetic Algorithms}
    \end{center}

    \begin{center}
    \textbf{Claudio Sebastian Castillo}
    \end{center}

    \vspace{1cm}

    In machine‑learning tasks, the amount of available training data strongly affects feature‑selection procedures and becomes particularly critical in high‑dimensional, noisy settings. Most feature‑selection methods are sensitive to sample size; when Genetic Algorithms (GA) drive the search, data scarcity degrades the fitness function and, consequently, the algorithm's effectiveness. To mitigate this problem, we integrate feature selection with a preceding synthetic‑data generation step based on Variational Autoencoders (VAE). The resulting pipeline —VAE augmentation followed by GA‑based selection— artificially expands the information available and applies it to demanding feature‑selection scenarios, yielding superior results compared with the same process without augmentation. We detail the VAE–GA integration and report experiments on five benchmark datasets widely cited in the literature: **Leukemia, Gisette, Madelon, GCM,** and **ALL Leukemia**. We also describe the model architectures used in each stage of the pipeline.

  chapters:
    - index.qmd    
    - references.qmd
  appendices:
    - Apendices/AppendixA.qmd  
    - Apendices/AppendixB.qmd
  repo-url: https://github.com/castillosebastian/ealab
  repo-actions: [edit, source, issue]
  search: true
thesis:
  supervisor: 
    name: Matías Gerard y Leandro Vignolo
    url: https://sinc.unl.edu.ar/
  degree-name: Maestría en Minería de Datos
  university: Universidad Tecnológica Nacional 
  department: Regional Paraná
  group: UTN     
  quotation:
    text: A mis universos Morella, Sofía, Joaquín y Manuel. A mi amada Verónica.    
  acknowledgements: "Frontmatter/acknowledgements.tex"  
  logo: images/utn_logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
    mainfont: "Times New Roman"
    classoption: "oneside"
    include-in-header:
      - custom-margins.tex
      - text: |
          \usepackage{mathptmx}

